version: '2'
services:
  mongo:
    image: mongo
  redis:
    image: redis
    ports:
      - '6371:6379'
  coral:
    build: ./Layer 2 - Application/coral
  coraline:
    build: ./Layer 2 - Application/coraline
