version: '2'
services:

  mongo:
    image: mongo

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - '6371:6379'

  # realm:
  #   build:
  #     context: ./Layer 2 - Application/realm
  #     dockerfile: Dockerfile
  coral:
    container_name: Coral
    ports:
      - '3001:8080'
    command: [ "host.docker.internal", "8080" ]
    build:
      context: ./
      dockerfile: "Layer 2 - Application/coral/Dockerfile"
    deploy:
      mode: replicated
      replicas: 4
  # coraline:
  #   build:
  #     context: ./Layer 2 - Application/coraline
  #     dockerfile: coraline/Dockerfile
  #   # build: ./Layer 2 - Application/coraline
