version: '3.8'
services:
  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - '6379:6379'
  coral:
    container_name: Coral
    depends_on:
      - redis
    ports:
      - '8000:8000'
      - '9000:9000'
    build:
      context: ./
      dockerfile: Layer 2 - Application/coral/Dockerfile
  coraline-1:
    container_name: Coraline-1
    depends_on:
      - redis
      - coral
    ports:
      - '7001:7000'
    build:
      context: ./
      dockerfile: Layer 2 - Application/coraline/Dockerfile
  coraline-2:
    container_name: Coraline-2
    depends_on:
      - redis
      - coral
    ports:
      - '7002:7000'
    build:
      context: ./
      dockerfile: Layer 2 - Application/coraline/Dockerfile
