version: '2'
services:

  mongo:
    image: mongo

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - '6371:6379'

  # realm:
  #   build:
  #     context: ./Layer 2 - Application/realm
  #     dockerfile: Dockerfile

  coral:
    network_mode: "host"
    container_name: Coral
    ports:
      - '0:8000'
    command: [ "host.docker.internal:8000" ]
    build:
      context: ./
      dockerfile: "Layer 2 - Application/coral/Dockerfile"
    # deploy:
    #   mode: replicated
    #   replicas: 4

  coraline-1:
    build:
      context: ./Layer 2 - Application/coraline
      dockerfile: coraline/Dockerfile

  coraline-2:
    build:
      context: ./Layer 2 - Application/coraline
      dockerfile: coraline/Dockerfile
      
  # coraline-3:
  #   build:
  #     context: ./Layer 2 - Application/coraline
  #     dockerfile: coraline/Dockerfile
      
  # coraline-4:
  #   build:
  #     context: ./Layer 2 - Application/coraline
  #     dockerfile: coraline/Dockerfile
