@startuml vues-cetc-performance

component Web as web #SkyBlue
component Redis as redis #Pink
component Coral as coral #Coral {
	component TcpServer
	component RedisClient as RedisClientCoral
	component RocketApi as RocketApiCoral

}
component Coraline as coraline #Coral {
	component TcpClient
	component "RedisClient (dev)" as RedisClientCoraline
	component "RocketApi (dev)" as RocketApiCoraline
}

redis <-0)- RedisClientCoral : TCP
redis <.0). RedisClientCoraline : TCP
web -(0-> RocketApiCoral : HTTP
web .(0.> RocketApiCoraline : HTTP
TcpServer <-0)- TcpClient : TCP

@enduml
